# Generated by Django 5.1.1 on 2024-09-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_disponibilite_reserved_alter_reservation_ressource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='adresse',
            field=models.CharField(default='Conakry', max_length=100),
            preserve_default=False,
        ),
    ]
